### PR TITLE
Working library with a simple test example

### PR DESCRIPTION
**Pull request by k0d**
I've tested this with using Blinka with a FT232H connecting to a board I designed myself with a MidasDisplays panel.

Screenshot_2021-03-02_at_22 51 51

### CODE REVIEW

**Review by makermelissa — COMMENTED** [review]
Looks great. The only thing I see is I noticed there is an `adafruit_st7565.py` and a `build/lib/adafruit_st7565.py` that appear to be duplicates. Was that intentional?

**Comment by k0d** [comment]
I've removed that file, and another stray one in the examples folder....they slipped into the commit, cheeky little files!

**Review by makermelissa — APPROVED** [review]
Looks great. Thanks!

**Comment by ladyada** [comment]
wow awesome thank you!

**Pull request merged**
